### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by alef** [alef/15BN#1]
- [x] Add a spectator slot
- [ ] Re-test #2 with ALiVE-lite
- [ ] Subtitles off seems not showing support radio messages
- [ ] FRIES doens't work with combat support: http://alivemod.com/forum/1832-ace-s-fastroping-and-combat-support-transport-won-t-make-someti
- [ ] Test save event after last player exits
- [ ] Fill vehicles including heli with medic  stuff
- [ ] Document into Field Manual
- [ ] Find and fix ACRE message about desync inventory from Arsenal
- [x] BLUFOR as default side
- [x] Add Explosive layout
- [x] Put playable units back together
- [x] CIV at Pyrgos even when away
- [x] WD Vehicles
- [x] Remove ACRE radios
- [x] Restore microDAGR map
- [x] Tone enemy survivability down
- [x] Fix ALiVE units getting out of heli being hurt
- [x] Add and test HC
- [x] Fix A-10 taxing back to station
- [x] Add IR marker to layouts
- [x] Logistics conflicts with helipads of combat support
- [x] Reduce lobby-to-mission timing and fix seagull spawn
- [x] "Unknown game mode" on loading
- [x] Add empty RHS airplanes at base for be used by players
- [x] Let BLUF LOGCOM dynamic mode use friendly side of island
- [x] Recon layout
- [x] Combat Support
- [x] Airplanes
- [x] Add RHS specific logistic support items
